; エフェクトの設定
; UTF-8で記述する
; ProgramData\aviutl2\effect.confで設定を上書き出来る

; 以前のスクリプトのeffect()関数の引数の読み替え (互換対応)
[OldScript.グラデーション]
color=開始色
color2=終了色
no_color=開始色
no_color2=終了色
blend=合成モード
type=形状
[OldScript.ノイズ]
type=ノイズの種類
seed=シード
mode=合成モード
[OldScript.単色化]
color=色
[OldScript.マスク]
type=マスクの種類
[OldScript.発光]
color=光色
no_color=光色
[OldScript.閃光]
color=光色
no_color=光色
mode=合成モード
[OldScript.色調補正]
ｺﾝﾄﾗｽﾄ=コントラスト
[OldScript.縁取り]
color=縁色
[OldScript.リサイズ]
ドット数でサイズ指定=ピクセル数でサイズ指定
[OldScript.ルミナンスキー]
ぼかし=輝度範囲
type=モード
[OldScript.カラーキー]
color_yc=基準色
[OldScript.クロマキー]
color_yc=基準色
[OldScript.特定色域変換]
color_yc=変換前の色
color_yc2=変換後の色
[OldScript.ドロップシャドウ]
color=影色
[OldScript.エッジ抽出]
color=色
[OldScript.ライト]
color=色
[OldScript.色ずれ]
type=色ずれの種類
[OldScript.ディスプレイスメントマップ]
type=変形方法
name=マップの種類
param0=変形X
param1=変形Y
[OldScript.グロー]
color=光色
no_color=光色
type=形状
[OldScript.ワイプ]
type=ワイプの種類
name=ワイプの種類
[OldScript.テキスト]
text=テキスト
font=フォント
type=文字装飾
align=文字揃え
color=文字色
color2=影・縁色
spacing_x=字間
spacing_y=行間
autoadjust=オブジェクトの長さを自動調節
移動座標上に表示する=移動座標上に表示
[OldScript.動画ファイル]
file=ファイル
[OldScript.画像ファイル]
file=ファイル
[OldScript.音声ファイル]
file=ファイル
[OldScript.図形]
type=図形の種類
name=図形の種類
color=色
[OldScript.標準描画]
blend=合成モード
回転=Z軸回転

; 以前のスクリプトのエフェクト名の読み替え (互換対応)
[OldScript]
拡張描画=標準描画
標準再生=音声再生

; 以前のスクリプトの移動モードの読み替え (互換対応)
[OldScript.trackmode]
1=直線移動
2=補間移動
3=瞬間移動
4=直線移動
5=移動量指定
6=ランダム移動
7=補間移動
8=反復移動
SingleSection=4

; 以前のスクリプトのアニメーション効果の番号 (互換対応)
[OldScript.アニメーション効果]
0=震える
1=振り子
2=弾む
3=座標の拡大縮小(個別オブジェクト)
4=画面外から登場
5=ランダム方向から登場
6=拡大縮小して登場
7=ランダム間隔で落ちながら登場
8=弾んで登場
9=広がって登場
10=起き上がって登場
11=何処からともなく登場
12=反復移動
13=座標の回転(個別オブジェクト)
14=立方体(カメラ制御)
15=球体(カメラ制御)
16=砕け散る
17=点滅
18=点滅して登場
19=簡易変形
20=簡易変形(カメラ制御)
21=リール回転
22=万華鏡
23=円形配置
24=ランダム配置

; 以前のスクリプトのカスタムオブジェクトの番号 (互換対応)
[OldScript.カスタムオブジェクト]
0=集中線
1=走査線
2=カウンター
3=レンズフレア
4=雲
5=星
6=雪
7=雨
8=ランダム小物配置(カメラ制御)
9=ライン(移動軌跡)
10=扇型
11=多角形
12=周辺ボケ光量
13=フレア
14=水面

; 以前のスクリプトのカメラ効果の番号 (互換対応)
[OldScript.カメラ効果]
0=手ぶれ
1=目標中心回転
2=目標サイズ固定視野角
