/*** Autogenerated by WIDL 11.12 from /home/runner/build_wine/wine/include/tpcshrd.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __tpcshrd_h__
#define __tpcshrd_h__

/* Forward declarations */

/* Headers for imported files */

#include <unknwn.h>
#include <objidl.h>
#include <oaidl.h>
#include <msinkaut.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TABLET_DISABLE_PRESSANDHOLD        0x00000001
#define WM_TABLET_DEFBASE                  0x02c0
#define WM_TABLET_MAXOFFSET                0x20
#define WM_TABLET_ADDED                    (WM_TABLET_DEFBASE + 8)
#define WM_TABLET_DELETED                  (WM_TABLET_DEFBASE + 9)
#define WM_TABLET_FLICK                    (WM_TABLET_DEFBASE + 11)
#define WM_TABLET_QUERYSYSTEMGESTURESTATUS (WM_TABLET_DEFBASE + 12)
typedef USHORT SYSTEM_EVENT;
typedef DWORD TABLET_CONTEXT_ID;
typedef enum _PROPERTY_UNITS {
    PROPERTY_UNITS_DEFAULT = 0,
    PROPERTY_UNITS_INCHES = 1,
    PROPERTY_UNITS_CENTIMETERS = 2,
    PROPERTY_UNITS_DEGREES = 3,
    PROPERTY_UNITS_RADIANS = 4,
    PROPERTY_UNITS_SECONDS = 5,
    PROPERTY_UNITS_POUNDS = 6,
    PROPERTY_UNITS_GRAMS = 7,
    PROPERTY_UNITS_SILINEAR = 8,
    PROPERTY_UNITS_SIROTATION = 9,
    PROPERTY_UNITS_ENGLINEAR = 10,
    PROPERTY_UNITS_ENGROTATION = 11,
    PROPERTY_UNITS_SLUGS = 12,
    PROPERTY_UNITS_KELVIN = 13,
    PROPERTY_UNITS_FAHRENHEIT = 14,
    PROPERTY_UNITS_AMPERE = 15,
    PROPERTY_UNITS_CANDELA = 16
} PROPERTY_UNITS;
typedef struct _PROPERTY_METRICS {
    LONG nLogicalMin;
    LONG nLogicalMax;
    PROPERTY_UNITS Units;
    FLOAT fResolution;
} PROPERTY_METRICS;
typedef struct _PROPERTY_METRICS *PPROPERTY_METRICS;
typedef struct _PACKET_PROPERTY {
    GUID guid;
    PROPERTY_METRICS PropertyMetrics;
} PACKET_PROPERTY;
typedef struct _PACKET_PROPERTY *PPACKET_PROPERTY;
typedef struct tagSYSTEM_EVENT_DATA {
    BYTE bModifier;
    WCHAR wKey;
    LONG xPos;
    LONG yPos;
    BYTE bCursorMode;
    DWORD dwButtonState;
} SYSTEM_EVENT_DATA;
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __tpcshrd_h__ */
